spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

    jpa:
    hibernate:
      ddl-auto: none   # Do not auto-generate schema; use Liquibase for migrations
    show-sql: true      # Set to true if you want to see SQL statements in the console
    properties:
      hibernate:
        format_sql: true # Nicely formats SQL output in the console

  liquibase:
    enabled: true
    change-log: classpath:db.master.yaml  # Points to the master changelog file
    drop-first: false

  # Hibernate settings for efficient performance with large datasets (optional)
  jpa:
    properties:
      hibernate.jdbc.batch_size: 30
      hibernate.order_inserts: true
      hibernate.order_updates: true

# Server settings (optional)
server:
  port: ${SERVER_PORT}  # Define the port your application will run on

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG  # Show SQL in logs if needed
    org.hibernate.type: TRACE # Show SQL parameter values in logs
