spring:
  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # JWT Configuration
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration-time: ${JWT_EXPIRATION}000  # Convert to milliseconds

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SUPPORT}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: ${LOGGING_ROOT_LEVEL}
    org.hibernate.SQL: ${LOGGING_HIBERNATE_SQL}
    org.hibernate.type: ${LOGGING_HIBERNATE_TYPE}

  # Optional .env File Import
config:
  import: optional:file:.env
