spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
    hibernate:
      ddl-auto: none   # Do not auto-generate schema; use Liquibase for migrations
    show-sql: true      # Set to true if you want to see SQL statements in the console
    properties:
      hibernate:
        format_sql: true # Nicely formats SQL output in the console

  liquibase:
    enabled: true
    change-log: classpath:db.master.yaml  # Points to the master changelog file
    drop-first: false

  # Hibernate settings for efficient performance with large datasets (optional)
  jpa:
    properties:
      hibernate.jdbc.batch_size: 30
      hibernate.order_inserts: true
      hibernate.order_updates: true


  mail:
    username: ${MAIL_SUPPORT}
    password: ${MAIL_PASSWORD}
server:
  port: 8080  # Define the port your application will run on

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG  # Show SQL in logs if needed
    org.hibernate.type: TRACE # Show SQL parameter values in logs

security:
  jwt:
    secret-key: 134256378948371526789301823781252891527531226784172461624626416451271264671526456125416246241247165246124615624516541171245164615124124

    expiration-time: 87468712649

