spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebankify
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /api